In [120]:
import jellyfish
from pyjarowinkler import distance

jellyfish.jaro_winkler('POBOX1692MORGANTON','POBOX1695MORRISTOWN')

0.8814954051796157

In [86]:

import pandas as pd
df_npa = pd.read_csv(r'C:\Users\KC\Desktop\EssilorWP\NPA_Processed.csv', index_col=0)
df_macola = pd.read_csv(r"C:\Users\KC\Desktop\WhitespaceProject\Macola.csv")
df_npa = df_npa[df_npa.columns.drop(list(df_npa.filter(regex='Other Provider Identifier')))]
df_npa = df_npa[df_npa.columns.drop(list(df_npa.filter(regex='Healthcare Provider Taxonomy')))] 
df_npa = df_npa[df_npa.columns.drop(list(df_npa.filter(regex='Healthcare Provider Primary Taxonomy')))]
df_npa = df_npa[df_npa.columns.drop(list(df_npa.filter(regex='Provider License Numb')))]
df_npa.shape

(140952, 54)

In [87]:
import re
check = 'GOROVOY MD EYE-SPECIALISTS,12381* .S CLEVELAND AVE #300'
re.sub('[^a-zA-Z0-9]', '', check)

'GOROVOYMDEYESPECIALISTS12381SCLEVELANDAVE300'

In [143]:
df_macola.columns

Index(['Macola/Company ID', 'Account Name', 'Shipping Street',
       'Shipping Address Line 1', 'Shipping Address Line 2',
       'Shipping Address Line 3', 'Shipping City', 'Shipping State/Province',
       'Shipping Zip/Postal Code', 'Latitude_WD', 'Longitude_WD', 'Phone',
       'Email - Primary', 'Website', 'Primary Lab Channel', 'Unnamed: 15',
       'Primary Laboratory (Sales)', 'Practice Name',
       'Practice Street Address 1', 'Practice Street Address 2',
       'Practice City', 'Practice State', 'Practice Zip', 'Practice Phone',
       'Practice email', 'Practice URL'],
      dtype='object')

In [122]:
import re
string = 'fsfdf'
str(int(re.search(r'\d+', string)))

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

In [136]:
import re
#m = re.search('STE (\d+)|SUITE (\d+)', 'series[SUITE 37]-03th_July_2010-YouTube', re.IGNORECASE)
#m.group(1)

str = ""
a = re.findall(r'\d+', str)
print(a)

[]

In [82]:
import pandas as pd
import jellyfish
from pyjarowinkler import distance
import re
df_npa = pd.read_csv(r'C:\Users\KC\Desktop\EssilorWP\NPA_Processed.csv', index_col=0)
df_macola = pd.read_csv(r"C:\Users\KC\Desktop\WhitespaceProject\Macola.csv")
df_npa = df_npa[df_npa.columns.drop(list(df_npa.filter(regex='Other Provider Identifier')))]
df_npa = df_npa[df_npa.columns.drop(list(df_npa.filter(regex='Healthcare Provider Taxonomy')))] 
df_npa = df_npa[df_npa.columns.drop(list(df_npa.filter(regex='Healthcare Provider Primary Taxonomy')))]
df_npa = df_npa[df_npa.columns.drop(list(df_npa.filter(regex='Provider License Numb')))]

df_npa = df_npa.dropna(axis=1, how='all')

df_npa1 = df_npa.dropna(subset=['Provider Organization Name (Legal Business Name)'])
df_npa = pd.concat([df_npa,df_npa1])
df_npa = df_npa.drop_duplicates(keep=False)


'''cols = ['Shipping Address Line 1', 'Shipping Address Line 2', 'Shipping Address Line 3', 'Shipping City']
df_macola['check1'] = df_macola[cols].apply(lambda x: ','.join(x.dropna()), axis=1)
cols_npa1 = ['Provider First Line Business Mailing Address', 'Provider Second Line Business Mailing Address', 'Provider Business Mailing Address City Name']
df_npa['check1'] = df_npa[cols_npa1].apply(lambda y: ','.join(y.dropna()), axis=1)

npa_index = []
address = df_macola['check1'].tolist()
for index, row in df_npa_stage1.iterrows():
    if (row['check1'] in address):
        npa_index.append(index)
        
df_npa = df_npa.drop(npa_index)'''

"cols = ['Shipping Address Line 1', 'Shipping Address Line 2', 'Shipping Address Line 3', 'Shipping City']\ndf_macola['check1'] = df_macola[cols].apply(lambda x: ','.join(x.dropna()), axis=1)\ncols_npa1 = ['Provider First Line Business Mailing Address', 'Provider Second Line Business Mailing Address', 'Provider Business Mailing Address City Name']\ndf_npa['check1'] = df_npa[cols_npa1].apply(lambda y: ','.join(y.dropna()), axis=1)\n\nnpa_index = []\naddress = df_macola['check1'].tolist()\nfor index, row in df_npa_stage1.iterrows():\n    if (row['check1'] in address):\n        npa_index.append(index)\n        \ndf_npa = df_npa.drop(npa_index)"

In [84]:
df_macola['Shipping Address Line2']

KeyError: 'Shipping Address Line2'

In [107]:
s = '107S33M15H'    
prefix = s.rpartition('M')[0]
prefix

'107S33'

In [113]:
df_npa[['Provider First Line Business Mailing Address',
       'Provider Second Line Business Mailing Address',]]

,Provider First Line Business Mailing Address,Provider Second Line Business Mailing Address
30,1107 MANTUA PIKE,STE 722
33,169 N MIDDLETOWN RD,NaN
36,31519 WINTERPLACE PKWY,STE 1
77,1420 S 28TH AVE,NaN
89,7815 N KNOXVILLE AVE,NaN
112,402 S COX ST,NaN
140,65 BELKNAP ST,STE 1
180,3415 GOLDEN RD,NaN
205,10260 WESTHEIMER RD,STE 580
240,2808 FORSYTHE AVE,NaN
249,14210 CULVER DR,STE F
256,1400 WELLBROOK CIR NE,STE 100
268,2880 DAUPHIN ST,NaN
296,PO BOX 38157,NaN
298,99 US ROUTE 1 BYP STE A,NaN
304,123 HOSPITAL DR,SUITE 1002
306,660 S EUCLID AVE,C B 8096
312,3415 GOLDEN RD,NaN
332,1420 S 28TH AVE,NaN
354,2652 GEORGE WASHINGTON MEMORIAL HWY,STE 1
377,155 BORTHWICK AVE,SUITE 200 EAST
448,1620 COUNTRY CLUB RD,SUITE D
460,2935 MAPLE AVE,NaN
464,1002 SEATON LN,NaN
481,453 SUMNER AVE,NaN
483,31519 WINTERPLACE PKWY,STE 1
516,6770 MAYFIELD RD,STE 338
520,5430 FREDERICKSBURG RD,STE 100
624,12381 S CLEVELAND AVE,STE 300
635,12381 S CLEVELAND AVE,STE 300
...,...,...
6124748,415 L ST NW APT 444,NaN
6124773,2422 AMBLER AVE,NaN
6124832,702 SW 8TH ST,NaN
6124874,32100 TELEGRAPH RD,NaN
6124895,233 SPRING ST FL 6,NaN
6124896,233 SPRING ST FL 6,NaN
6125101,32100 TELEGRAPH RD STE 205,NaN
6125150,9700 S MCCARRAN BLVD,NaN
6125180,32100 TELEGRAPH RD STE 205,NaN
6125240,504 E CENTER ST,NaN
6125500,6002 SLIDE ROAD,NaN
6125512,140 TRINITY PL STE B,NaN
6125615,2435 COMMERCE AVE BLDG 2200,NaN
6125619,535 S FERDON BLVD STE B,NaN
6125728,5471 NORMAN CT,BLDG 9250
6126108,1616 GATES AVE,NaN
6126123,2828 ALMOND ST,NaN
6126169,1075 EASTON AVE STE 1-2B,NaN
6126268,1950 OLD GALLOWS RD STE 520,NaN
6126315,6536 SW 134TH PL,NaN
6126362,32100 TELEGRAPH RD STE 205,NaN
6126507,130 N BALLARD AVE,NaN
6126568,3541 W 95TH ST,NaN
6126648,214 N FRANKLIN AVENUE,NaN
6126650,458 27TH AVE APT 4,NaN
6126809,2435 COMMERCE AVE BLDG 2200,NaN
6126962,1486 WATERBURY RD,NaN
6127159,PO BOX 18331,NaN
6127165,5427 TIMBER POST ST,NaN
6127248,201 RACINE DR,NaN

In [138]:
[] == []

True

In [141]:
df_npa.columns

Index(['NPI', 'Entity Type Code', 'Replacement NPI',
       'Employer Identification Number (EIN)',
       'Provider Organization Name (Legal Business Name)',
       'Provider Last Name (Legal Name)', 'Provider First Name',
       'Provider Middle Name', 'Provider Name Prefix Text',
       'Provider Name Suffix Text', 'Provider Credential Text',
       'Provider Other Organization Name',
       'Provider Other Organization Name Type Code',
       'Provider Other Last Name', 'Provider Other First Name',
       'Provider Other Middle Name', 'Provider Other Name Prefix Text',
       'Provider Other Name Suffix Text', 'Provider Other Credential Text',
       'Provider Other Last Name Type Code',
       'Provider First Line Business Mailing Address',
       'Provider Second Line Business Mailing Address',
       'Provider Business Mailing Address City Name',
       'Provider Business Mailing Address State Name',
       'Provider Business Mailing Address Postal Code',
       'Provider Business Mailing Address Country Code (If outside U.S.)',
       'Provider Business Mailing Address Telephone Number',
       'Provider Business Mailing Address Fax Number',
       'Provider First Line Business Practice Location Address',
       'Provider Second Line Business Practice Location Address',
       'Provider Business Practice Location Address City Name',
       'Provider Business Practice Location Address State Name',
       'Provider Business Practice Location Address Postal Code',
       'Provider Business Practice Location Address Country Code (If outside U.S.)',
       'Provider Business Practice Location Address Telephone Number',
       'Provider Business Practice Location Address Fax Number',
       'Provider Enumeration Date', 'Last Update Date',
       'NPI Deactivation Reason Code', 'NPI Deactivation Date',
       'NPI Reactivation Date', 'Provider Gender Code',
       'Authorized Official Last Name', 'Authorized Official First Name',
       'Authorized Official Middle Name',
       'Authorized Official Title or Position',
       'Authorized Official Telephone Number', 'Is Sole Proprietor',
       'Is Organization Subpart', 'Parent Organization LBN',
       'Parent Organization TIN', 'Authorized Official Name Prefix Text',
       'Authorized Official Name Suffix Text',
       'Authorized Official Credential Text'],
      dtype='object')

In [142]:
l = [1,2,3]
b = [2,3]

TypeError: unsupported operand type(s) for -: 'list' and 'list'